### ISSUE TITLE
More defensive checks on DESTINATION path value and improved help text

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/cellcutter#7]
DESTINATION should be required to end in `.zarr` and not exist, to avoid the user accidentally overwriting data (zarr.create first removes the target directory recursively if it exists). For someone who knows what they're doing, a `-f/--force` argument could override both of these checks.

Also the `help` text for DESTINATION should make it clear the value must end in `.zarr`. Note the actual arg name (and corresponding Namespace attribute) can be separated from the help text placeholder using the `metavar` arg to `add_argument`. For example you might use `add_argument("destination", metavar="destination.zarr")`.

**Comment by clemenshug** [comment]
Sounds good! If the user provides a destination that doesn't end in `.zarr`, would you prefer if I added it or should I raise an error?

**Comment by jmuhlich** [comment]
I vote error. If you implement `-f/--force` then you would just use it as-is with no correction or error message.
